# .goreleaser.yml
project_name: go-aws-sso
builds:
  - env: [ CGO_ENABLED=0 ]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: "go-aws-sso"
    dir: .
    main: ./cmd/go-aws-sso

release:
  draft: true

changelog:
  skip: false

  # Changelog generation implementation to use.
  #
  # Valid options are:
  # - `git`: uses `git log`;
  # - `github`: uses the compare GitHub API, appending the author login to the changelog.
  # - `gitlab`: uses the compare GitLab API, appending the author name and email to the changelog.
  # - `github-native`: uses the GitHub release notes generation API, disables the groups feature.
  #
  # Defaults to `git`.
  use: git
  sort: asc


  # TODO: Groups are currently not working as expected
  # Group commits messages by given regex and title.
  # Order value defines the order of the groups.
  # Proving no regex means all commits will be grouped under the default group.
  # Groups are disabled when using github-native, as it already groups things by itself.
  #
#  groups:
#    - title: Features
#      regexp: "^\\[feature\\].*$"
#      order: 0
#    - title: 'Bug Fixes'
#      regexp: '^\[bugfix\].*'
#      order: 1
#    - title: Others
#      regexp: '^\[misc\].*'
#      order: 999

  filters:
    exclude:
      - '^docs:'
      - '^\w.*$'
